# Generated by Django 5.2 on 2025-05-11 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v_users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
