# Generated by Django 5.2 on 2025-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_post', '0002_tag_alter_post_options_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon_images',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
